### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by Plemeur** [adolfocorreia/DGM#1]
Hi, according to this paper :https://arxiv.org/pdf/1811.08782.pdf
the loss function in line 55 of merton.py should be : 

f = -0.5*lambd**2*V_x**2 + (V_t + r*x1* **V** )*V_xx

Have you been using V_x instead of V for a reason ?

**Comment by adolfocorreia** [comment]
Unfortunately, the equation in the paper (page 57) is incorrect. There should be no <img src="https://latex.codecogs.com/gif.latex?-\tfrac{\lambda^2}{2&space;\sigma^2}" title="-\frac{\lambda^2}{2 \sigma^2}" /> term inside the parentheses and the other term should be <img src="https://latex.codecogs.com/gif.latex?r&space;x&space;\partial_xH" title="r x \partial_xH" />. The code in merton.py is correct.
