### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by ghost** [adolfocorreia/DGM#2]
Is the DGM network optimized for GPU? The code as it stands does not utilize GPU. Changing the DGM network to feed-forward network fixes this problem though (I can see the GPU being used at full capacity). The training time with DGM network is too high with CPU unfortunately. 

Any help is appreciated.

**Comment by adolfocorreia** [comment]
It's been a while since I last used this code, but we ran everything using GPUs at the time. As far as I know, all we had to do was install the tensorflow-gpu package. However, that was before tensorflow v2 was launched and things might have changed since then. Try using tensorflow v1.

**Comment by goutham-epfl** [comment]
Ok thank you for the response.

**Comment by ghost** [comment]
Okay. Thank you for the response.
